# Use an image that includes both Ruby and Node.js
FROM ruby:3.2.2 AS development

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && \
    apt-get install -y nodejs npm

# Copy Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Install Ruby dependencies
RUN bundle install

# Copy package.json and package-lock.json
COPY package*.json ./

# Install JavaScript dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port (if necessary)
EXPOSE 3000

# Set default command to run the Rails server
CMD ["rails", "server", "-b", "0.0.0.0"]
