default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_website_development

test:
  <<: *default
  database: my_website_test

production:
  <<: *default
  database: my_website_production
  username: my_website
  password: <%= ENV['DATABASE_URL'] %>
